name: Publish NuGet packages
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Publish Core Project
        id: publish_core_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Core/RemoteMediatr.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}

      - name: Publish Server Project
        id: publish_server_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Server/RemoteMediatr.Server.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}

      - name: Publish Client Project
        id: publish_client_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Client/RemoteMediatr.Client.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
